import Navbar from "./(shared)/components/Navbar";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
    title: "Inion VR",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className='my-1'>
            <body className={poppins.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
