import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins, Raleway } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
    title: "Inion VR",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className=''>
            <Navbar />
            <body className={`${poppins.className}`}>{children}</body>
        </html>
    );
}
